title: LAKIS Tech
email: jacek.lakis@gmail.com
description: >-
  LAKIS Tech - Jacek J. Łakis. DX | Platform | SRE | Cloud | Backend | Apps
baseurl: ""
repository: "jjlakis/jjlakis.github.io"
url: "https://www.lakis.tech"
twitter_username: jjlakis
github_username:  jjlakis
logo: "img/small4.svg"

author:
  name: "Jacek J. Łakis"
  avatar: "/img/ja.jpeg"
  bio: "DX, Platform, SRE, Cloud, Backend to name a few"
  location: "Gdańsk, Poland"
  links:
    - label: "lakis.tech"
      icon: "fas fa-fw fa-link"
      url: "https://www.lakis.tech"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/jjlakis"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin-in"
      url: "https://www.linkedin.com/in/jjlakis/"
    - label: "Medium"
      icon: "fab fa-fw fa-medium"
      url: "https://medium.com/@jjlakis"


# Build settings
include: ["_pages"]
remote_theme: "jjlakis/minimal-mistakes@v0.0.1"
plugins:
  - jekyll-feed
  - jekyll-include-cache
