title: LAKIS Tech
email: jacek.lakis@gmail.com
description: >-
  LAKIS Tech - Jacek J. Łakis. DX | Platform | SRE | Cloud | Backend | Apps
baseurl: ""
url: "https://www.lakis.tech"
twitter_username: jjlakis
github_username:  jjlakis

# Build settings
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
plugins:
  - jekyll-feed
  - jekyll-include-cache
